### ISSUE TITLE
ERROR: macs2 peak calling was not successful

### ISSUE THREAD

**Issue by aperreault** [aryeelab/hichipper#47]
Hello! I'm trying to test hichipper in my programming environment by running the following lines from the /tests/README.md:

hichipper call --out outputCallBAM --restriction-frags ../RestrictionFragmentFiles/hg19_MboI_resfrag.bed.gz --peaks chipseq/GM12878_SMC3_ChIPSeq_chr22.narrowPeak --skip-resfrag-pad --basic-qc --skip-diffloop --input-bam call_inputs/HiCUP_chr22.bam

hichipper --out combinedall --skip-diffloop yaml/example_COMBINED_ALL.yaml
hichipper --out combinedself --skip-diffloop yaml/example_COMBINED_SELF.yaml

First error: 
[u'outputCallvi/userSuppliedPeaks.bed.tmp_pad.bed.tmp']
Not fully supported yet!
What does this mean and what can I do to fix it?

Second error (applies to both the combined lines):
AttributeError: 'Namespace' object has no attribute 'maxgap'
ERROR: macs2 peak calling was not successful; make sure macs2 is in the environment and that *Pairs files exist for samples. Finally, note that only the narrowPeak file is being considered here, which may be a problem if you tried to do broad peak calling.
MACS2 is in my PATH so I'm not sure how to fix this one either.

I appreciate any help I can get!
-Andrea

**Comment by caleblareau** [comment]
Hi Andrea,

`call` mode is still under development and not fully supported. I’m hoping to finish it soon!

**Comment by aperreault** [comment]
Thanks for the quick response Caleb!
Any insights to the second error message I was getting?

**Comment by caleblareau** [comment]
Yes, sorry overlooked that second half…

Can you run hichipper keeping temporary files and then send me an `ls -lrth`? The error message is fairly generic but that should help quite a bit.

**Comment by aperreault** [comment]
bryan@venters-server:~/hichipper-master/tests
$ hichipper --out combinedall --keep-temp-files --skip-diffloop yaml/example_COMBINED_ALL.yaml
Mon Jul 02 17:42:44 CDT 2018: Starting hichipper pipeline v0.7.3
Mon Jul 02 17:42:44 CDT 2018: Parsing user parameters
Mon Jul 02 17:42:44 CDT 2018: .yaml file detected
Traceback (most recent call last):
  File "/home/bryan/anaconda2/bin/macs2", line 617, in <module>
    main()
  File "/home/bryan/anaconda2/bin/macs2", line 57, in main
    run( args )
  File "/home/bryan/anaconda2/lib/python2.7/site-packages/MACS2-2.1.2.dev0-py2.7-linux-x86_64.egg/MACS2/callpeak_cmd.py", line 56, in run
    options = opt_validate( args )
  File "/home/bryan/anaconda2/lib/python2.7/site-packages/MACS2-2.1.2.dev0-py2.7-linux-x86_64.egg/MACS2/OptValidator.py", line 193, in opt_validate
    options.argtxt += "# max. gap between significant sites = %d\n" % options.maxgap
AttributeError: 'Namespace' object has no attribute 'maxgap'
ERROR: macs2 peak calling was not successful; make sure macs2 is in the environment and that *Pairs files exist for samples. Finally, note that only the narrowPeak file is being considered here, which may be a problem if you tried to do broad peak calling.

bryan@venters-server:~/hichipper-master/tests
$ ls -lrth
total 64K
-rw-rw-r-- 1 bryan bryan 1.1K Jun  9 20:16 verifyHCP.py
-rw-rw-r-- 1 bryan bryan  652 Jun  9 20:16 test_cli.py
drwxrwxr-x 2 bryan bryan 4.0K Jun  9 20:16 resfrag
-rw-rw-r-- 1 bryan bryan 1.3K Jun  9 20:16 README.md
-rw-rw-r-- 1 bryan bryan    1 Jun  9 20:16 __init__.py
drwxrwxr-x 4 bryan bryan 4.0K Jun  9 20:16 hicpro_one
drwxrwxr-x 4 bryan bryan 4.0K Jun  9 20:16 hicpro
drwxrwxr-x 2 bryan bryan 4.0K Jun  9 20:16 correct_output
drwxrwxr-x 2 bryan bryan 4.0K Jun  9 20:16 chipseq
drwxrwxr-x 2 bryan bryan 4.0K Jun  9 20:16 call_inputs
drwxrwxr-x 2 bryan bryan 4.0K Jul  2 17:02 output1
drwxrwxr-x 2 bryan bryan 4.0K Jul  2 17:08 yaml
drwxrwxr-x 2 bryan bryan 4.0K Jul  2 17:09 output1.1
drwxrwxr-x 2 bryan bryan 4.0K Jul  2 17:11 outputCallBAM
drwxrwxr-x 2 bryan bryan 4.0K Jul  2 17:12 outputCallvi
drwxrwxr-x 2 bryan bryan 4.0K Jul  2 17:42 combinedall

**Comment by aperreault** [comment]
Caleb,

Wanted to check back in to see if you had any insights to the MACS2 error I described above. 

Thanks!
-Andrea

**Comment by caleblareau** [comment]
Sorry this got away from me... I actually need to see the files output directory (hard to know which one this is from this list?)

**Comment by aperreault** [comment]
Quite alright! I've been working on some other files, so here's a recap on commands and errors:
$ time hichipper --out output5 yaml/Mumbach_eachAll.yaml
Traceback (most recent call last):
  File "/home/bryan/anaconda2/bin/macs2", line 617, in <module> main()
  File "/home/bryan/anaconda2/bin/macs2", line 57, in main run( args )
  File "/home/bryan/anaconda2/lib/python2.7/site-packages/MACS2-2.1.2.dev0-py2.7-linux-x86_64.egg/MACS2/callpeak_cmd.py", line 56, in run options = opt_validate( args )
  File "/home/bryan/anaconda2/lib/python2.7/site-packages/MACS2-2.1.2.dev0-py2.7-linux-x86_64.egg/MACS2/OptValidator.py", line 193, in opt_validate options.argtxt += "# max. gap between significant sites = %d\n" % options.maxgap
AttributeError: 'Namespace' object has no attribute 'maxgap'
ERROR: macs2 peak calling was not successful; make sure macs2 is in the environment and that *Pairs files exist for samples. Finally, note that only the narrowPeak file is being considered here, which may be a problem if you tried to do broad peak calling.

Here's the directory info:
bryan@venters-server:/media/bryan/2Tb_Workspace/AP/HiChIP/hichipper/Mumbach-hichipper
$ ls -lrth
total 16K
drwxrwxr-x 4 bryan bryan 4.0K Oct  3 09:43 hicpro
drwxrwxr-x 2 bryan bryan 4.0K Oct  3 09:50 yaml
drwxrwxr-x 2 bryan bryan 4.0K Oct  3 10:28 output5
drwxrwxr-x 6 bryan bryan 4.0K Oct  3 10:42 z-archive

bryan@venters-server:/media/bryan/2Tb_Workspace/AP/HiChIP/hichipper/Mumbach-hichipper
$ cd output5/

bryan@venters-server:/media/bryan/2Tb_Workspace/AP/HiChIP/hichipper/Mumbach-hichipper/output5
$ ls -lrth
total 8.5G
-rw-rw-r-- 1 bryan bryan 5.7G Oct  3 10:28 Rep2.all.Pairs.tmp
-rw-rw-r-- 1 bryan bryan 2.9G Oct  3 10:29 Rep2.all.Pairs.bed.tmp
-rw-rw-r-- 1 bryan bryan 1019 Oct  3 10:29 output5.hichipper.log

Let me know if you need any other info!
-Andrea

**Comment by caleblareau** [comment]
As far as I can tell, everything in hichipper is working just fine. I’d recommend upgrading macs2?

**Comment by aperreault** [comment]
Interesting. Which version of macs should I be running for hichipper? I'm currently running macs2 2.1.2_dev

**Comment by aperreault** [comment]
Caleb,

Another question for you- I tried rerunning the test files. Below is the command  I used and the errors I got. 

$ hichipper --out output1 yaml/one.yaml
Wed Oct 10 10:07:31 CDT 2018: Starting hichipper pipeline v0.7.3
Wed Oct 10 10:07:31 CDT 2018: Parsing user parameters
Wed Oct 10 10:07:31 CDT 2018: .yaml file detected
Error: package ‘GenomeInfoDb’ could not be loaded
Execution halted
Wed Oct 10 10:07:32 CDT 2018: Processing d1
Wed Oct 10 10:07:32 CDT 2018: Total_PETs=164332898
Wed Oct 10 10:07:32 CDT 2018: Mapped_unique_quality_pairs=1888170
Wed Oct 10 10:07:32 CDT 2018: Mapped_unique_quality_valid_pairs=627403
Wed Oct 10 10:07:32 CDT 2018: Intersecting PETs with anchors
Error: The requested file (output1/userSuppliedPeaks.bed.tmp_pad.bed.tmprf.tmp) could not be opened. Error message: (No such file or directory). Exiting!
/home/bryan/anaconda2/lib/python2.7/site-packages/hichipper/interactionsCall.sh: line 36: --keep-temp-files: command not found
Wed Oct 10 10:07:32 CDT 2018: Something went wrong in determining peaks for anchor inference; rerun with the  flag to debug.
ERROR: something failed at the individual sample level; check the .log file for more info

Any insights into what's going wrong? 
Thanks,
-Andrea

**Comment by caleblareau** [comment]
Hmmm, looks like you are missing an R package in your system?

https://bioconductor.org/packages/release/bioc/html/GenomeInfoDb.html

**Comment by aperreault** [comment]
Okay, that's installed (I've never gotten that error when running the program)

Really what I think the issue is is the location of macs2. One error line says there's an error in bin/macs2 and the following line says there's an error in lib/python2.7/site-packages/MACS2. Do you know if the location of macs2 matters to hichipper? If so, how would I redirect the script to either of these locations?
