### ISSUE TITLE
could not find function "endsWith"

### ISSUE THREAD

**Issue by wlwtan** [aryeelab/hichipper#52]
I was trying out the installation guide.
Installation seems fine.
When I was trying this command,
`"/home/wlwtan/.local/bin/hichipper` --out output1 `yaml/one.yaml",`
it failed with these following error:
`Thu Aug 30 20:06:54 SGT 2018: Starting hichipper pipeline v0.7.3
Thu Aug 30 20:06:54 SGT 2018: Parsing user parameters
Thu Aug 30 20:06:54 SGT 2018: .yaml file detected
Error: could not find function "endsWith"
Execution halted
Thu Aug 30 20:07:00 SGT 2018: Processing d1
Thu Aug 30 20:07:01 SGT 2018: Total_PETs=164332898
Thu Aug 30 20:07:14 SGT 2018: Mapped_unique_quality_pairs=1888170
Thu Aug 30 20:07:14 SGT 2018: Mapped_unique_quality_valid_pairs=627403
Thu Aug 30 20:07:14 SGT 2018: Intersecting PETs with anchors
Error: The requested file (output1/userSuppliedPeaks.bed.tmp_pad.bed.tmprf.tmp) could not be opened. Error message: (No such file or directory). Exiting!
/home/wlwtan/.local/lib/python2.7/site-packages/hichipper/interactionsCall.sh: line 36: --keep-temp-files: command not found
Thu Aug 30 20:07:15 SGT 2018: Something went wrong in determining peaks for anchor inference; rerun with the  flag to debug.
ERROR: something failed at the individual sample level; check the .log file for more info
`
Not sure what have gone wrong.

Thank you.

**Comment by docdot** [comment]
Hi, 

Has anyone sorted it out?

I'm receiving the same error:

`
home:~/Desktop/Software/HiChipper$ ls
config.yaml  DpnII_resfrag_hg19.bed  HiChIP  HiCPro_analysis  requirements.R
home:~/Desktop/Software/HiChipper$ rm -r HiChIP/
home:~/Desktop/Software/HiChipper$ hichipper --out HiChIP config.yaml 
Thu Oct 11 13:29:11 CEST 2018: Starting hichipper pipeline v0.7.3
Thu Oct 11 13:29:11 CEST 2018: Parsing user parameters
Thu Oct 11 13:29:11 CEST 2018: .yaml file detected
Thu Oct 11 13:29:18 CEST 2018: Performing hichipper-modified background peak calling
Error: could not find function "endsWith"
Execution halted
Thu Oct 11 13:29:23 CEST 2018: Modified background signal; performing peak calling
Thu Oct 11 13:29:23 CEST 2018: MACS2 TEXT OUTPUT INCOMING
INFO  @ Thu, 11 Oct 2018 13:29:23: Read and build treatment bedGraph... 
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 617, in <module>
    main()
  File "/usr/local/bin/macs2", line 73, in main
    run( args )
  File "/usr/local/lib/python2.7/dist-packages/MACS2/bdgcmp_cmd.py", line 40, in run
    tbtrack = tbio.build_bdgtrack()
  File "MACS2/IO/BedGraphIO.pyx", line 97, in MACS2.IO.BedGraphIO.bedGraphIO.build_bdgtrack (MACS2/IO/BedGraphIO.c:1079)
IOError: [Errno 2] No such file or directory: 'HiChIP/adjustedTreatment.bdg.tmp'
INFO  @ Thu, 11 Oct 2018 13:29:23: Read and build bedGraph... 
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 617, in <module>
    main()
  File "/usr/local/bin/macs2", line 65, in main
    run( args )
  File "/usr/local/lib/python2.7/dist-packages/MACS2/bdgpeakcall_cmd.py", line 51, in run
    btrack = bio.build_bdgtrack(baseline_value=0)
  File "MACS2/IO/BedGraphIO.pyx", line 97, in MACS2.IO.BedGraphIO.bedGraphIO.build_bdgtrack (MACS2/IO/BedGraphIO.c:1079)
IOError: [Errno 2] No such file or directory: 'HiChIP/hichipper_qvalue.bdg.tmp'
mv: cannot stat 'HiChIP/hichipper_peaks.bed': No such file or directory
awk: fatal: cannot open file `HiChIP/allSamples_temporary_hichipperPeaks.bed' for reading (No such file or directory)
Error: could not find function "endsWith"
Execution halted
Do 11. Okt 13:29:28 CEST 2018: Processing HiC_input
Do 11. Okt 13:29:28 CEST 2018: Total_PETs=3375114
Do 11. Okt 13:29:28 CEST 2018: Mapped_unique_quality_pairs=2012134
Do 11. Okt 13:29:28 CEST 2018: Mapped_unique_quality_valid_pairs=892189
Do 11. Okt 13:29:28 CEST 2018: Intersecting PETs with anchors
Error: The requested file (HiChIP/allSamples_temporary_hichipperPeaks.bed_pad.bed.tmprf.tmp) could not be opened. Error message: (No such file or directory). Exiting!
/usr/local/lib/python2.7/dist-packages/hichipper/interactionsCall.sh: line 36: --keep-temp-files: command not found
Do 11. Okt 13:29:28 CEST 2018: Something went wrong in determining peaks for anchor inference; rerun with the  flag to debug.
ERROR: something failed at the individual sample level; check the .log file for more info
`
Thank you,

Raphael

**Comment by docdot** [comment]
Hi all, 
I have been able to sort out:
Basically, the R dependencies were not installed properly.

```
install_pkgs <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) install.packages(new.pkg, dependencies = TRUE, repos="https://cloud.r-project.org")
}
install_pkgs(c("data.table", "devtools", "foreach", "ggplot2", "knitr", "networkD3", "readr", "reshape2"))

source("https://bioconductor.org/biocLite.R")
install_pkgs_bioc <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) biocLite(new.pkg, dependencies = TRUE, repos="https://cloud.r-project.org")
}
install_pkgs_bioc(c("diffloop"))
```

In my case, this code was not able to install "diffloop" and neither was possible using directly the biocLite. (I'm using Ubuntu Mate 16.04 and R 3.4). I installed devtools and then I pulled straight from the github repository. 

The steps above were able to sort this issue out.
(a new one appeared, but I will open a new thread for it)

Best

Raphael
