### ISSUE TITLE
Issue with MACS Output

### ISSUE THREAD

**Issue by jlpulice** [aryeelab/hichipper#75]
Hi!

I am getting this issue when running hichipper:

Tue Aug 13 15:22:36 EDT 2019: .yaml file detected
Tue Aug 13 15:39:59 EDT 2019: Performing hichipper-modified background peak calling
Tue Aug 13 15:40:56 EDT 2019: Modified background signal; performing peak calling
Tue Aug 13 15:40:56 EDT 2019: MACS2 TEXT OUTPUT INCOMING
INFO  @ Tue, 13 Aug 2019 15:40:56: Read and build treatment bedGraph... 
Traceback (most recent call last):
  File "/n/data1/dfci/medonc/meyerson/jpulice/software/HiC-Pro/dependencies/pythonlib/bin/macs2", line 614, in <module>
    main()
  File "/n/data1/dfci/medonc/meyerson/jpulice/software/HiC-Pro/dependencies/pythonlib/bin/macs2", line 72, in main
    run( args )
  File "/n/data1/dfci/medonc/meyerson/jpulice/software/HiC-Pro/dependencies/pythonlib/lib/python2.7/site-packages/MACS2/bdgcmp_cmd.py", line 40, in run
    tbtrack = tbio.build_bdgtrack()
  File "MACS2/IO/BedGraphIO.pyx", line 97, in MACS2.IO.BedGraphIO.bedGraphIO.build_bdgtrack (MACS2/IO/BedGraphIO.c:1079)
IOError: [Errno 2] No such file or directory: 'hichipper_081319_test/adjustedTreatment.bdg.tmp'
INFO  @ Tue, 13 Aug 2019 15:40:57: Read and build bedGraph... 
Traceback (most recent call last):
  File "/n/data1/dfci/medonc/meyerson/jpulice/software/HiC-Pro/dependencies/pythonlib/bin/macs2", line 614, in <module>
    main()
  File "/n/data1/dfci/medonc/meyerson/jpulice/software/HiC-Pro/dependencies/pythonlib/bin/macs2", line 64, in main
    run( args )
  File "/n/data1/dfci/medonc/meyerson/jpulice/software/HiC-Pro/dependencies/pythonlib/lib/python2.7/site-packages/MACS2/bdgpeakcall_cmd.py", line 51, in run
    btrack = bio.build_bdgtrack(baseline_value=0)
  File "MACS2/IO/BedGraphIO.pyx", line 97, in MACS2.IO.BedGraphIO.bedGraphIO.build_bdgtrack (MACS2/IO/BedGraphIO.c:1079)
IOError: [Errno 2] No such file or directory: 'hichipper_081319_test/hichipper_qvalue.bdg.tmp'
mv: cannot stat ‘hichipper_081319_test/hichipper_peaks.bed’: No such file or directory

I have tabix and bgzip in the path and as far as I can tell I have all the R and python packages installed. Please suggest additional remedies! I am getting all the peak calls for each file as well as the bdg outputs for treatment and control, but that is it. Thanks!!

**Comment by caleblareau** [comment]
Can you send your execution command + the ls -lR of the execution directory?

**Comment by jlpulice** [comment]
I'm running this with 
hichipper --out hichipper_081319_test all.yaml

For every HiC-Pro it's generating these seven files:
-rw-rw-r-- 1 jlp52 jlp52  4028159097 Aug 11 20:10 AGS.all.Pairs.bed.tmp
-rw-rw-r-- 1 jlp52 jlp52 11036152258 Aug 11 20:06 AGS.all.Pairs.tmp
-rw-rw-r-- 1 jlp52 jlp52  2574487508 Aug 11 20:29 AGS_temporary_control_lambda.bdg
-rw-rw-r-- 1 jlp52 jlp52    23770936 Aug 11 20:29 AGS_temporary_peaks.narrowPeak
-rw-rw-r-- 1 jlp52 jlp52    26002529 Aug 11 20:29 AGS_temporary_peaks.xls
-rw-rw-r-- 1 jlp52 jlp52    18006622 Aug 11 20:29 AGS_temporary_summits.bed
-rw-rw-r-- 1 jlp52 jlp52  4178289458 Aug 11 20:29 AGS_temporary_treat_pileup.bdg
There's ~50 files so I won't send all of these but an example. Only these and the logs are generating. It seems it's stopping for each file before it generates the AGS_temporary_hichipperPeaks.bed file.

**Comment by caleblareau** [comment]
What are the contents of all.yaml?

**Comment by jlpulice** [comment]
peaks:
 - EACH,ALL
resfrags:
 - hg19_MboI_resfrag.bed
hicpro_output:
 - hicpro_runall_080519

The HiC-Pro directory has all the required files in it.

**Comment by caleblareau** [comment]
is `hg19_MboI_resfrag.bed` in your directory from execution? The process is failing when trying to compute the new hichipper-adjusted peaks.

**Comment by caleblareau** [comment]
if not, try maybe specifying it as an absolute file path?

**Comment by jlpulice** [comment]
It's in the root directory of both hicpro_runall_080519 as well as where the output hichipper_081319_test will go. I can change that to an absolute file path and see if that works!

**Comment by jlpulice** [comment]
Rerunning with it specified as an absolute path didn't work. Still getting the same error. Any recommendations to check?

**Comment by emilyklo** [comment]
Do you have htslib installed? I was having the same issue but installing htslib seemed to do the trick.

**Comment by shanwai1234** [comment]
I also have the same error reported, has this issue been resolved?
