### ISSUE TITLE
IOError: [Errno 2] No such file or directory: .log

### ISSUE THREAD

**Issue by Rseq** [aryeelab/hichipper#82]
Hi Caleb,

I am receiving the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/hichipper", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hichipper/cli.py", line 117, in main
    logf = open(out + "/" + out + ".hichipper.log", 'w')
IOError: [Errno 2] No such file or directory: u'/media/test/Data/Data/HiChIP/Paired_End/SMC1a_cohesin_HiChIP_Mumbach_paper/hichipper//media/test/Data/Data/HiChIP/Paired_End/SMC1a_cohesin_HiChIP_Mumbach_paper/hichipper.hichipper.log'
```
For this command:
`$ hichipper --out /media/test/Data/Data/HiChIP/Paired_End/SMC1a_cohesin_HiChIP_Mumbach_paper/hichipper /home/test/Desktop/Scripts/hichipper/hichipper_SMC1_HiChIP_data_paper.yaml`

And .yaml file and path to files look fine:

```
$less /home/test/Desktop/Scripts/hichipper/hichipper_SMC1_HiChIP_data_paper.yaml

peaks:
  - EACH,ALL
resfrags:
  - /media/test/Data/Genomes_ref/bowtie2/Hsapiens/digested_ref/DpnII_resfrag_hg19.bed
hicpro_output:
  - /media/test/Data/Data/HiChIP/Paired_End/SMC1a_cohesin_HiChIP_Mumbach_paper/hicpro

$ tree /media/test/Data/Data/HiChIP/Paired_End/SMC1a_cohesin_HiChIP_Mumbach_paper

/media/test/Data/Data/HiChIP/Paired_End/SMC1a_cohesin_HiChIP_Mumbach_paper
|-- hichipper
`-- hicpro
    `-- hic_results
        `-- data
            |-- SMC1_HiChIP_rep1
            |   `-- GSM2138328_v65_HiChIP_cohesin_r1-1.allValidPairs
            `-- SMC1_HiChIP_rep2
                `-- GSM2138330_v65_HiChIP_cohesin_r2-1.allValidPairs
```

Any idea what it can be?
I'm using the latest hichipper version 

Thanks,

**Comment by caleblareau** [comment]
Based on the last line I/O error, I think the error has to do with how you've specified the output path (I didn't write this to be terribly intelligent). Based on this file path: `/media/test/Data/Data/HiChIP/Paired_End/SMC1a_cohesin_HiChIP_Mumbach_paper/hichipper//media/test/Data/Data/HiChIP/Paired_End/SMC1a_cohesin_HiChIP_Mumbach_paper/hichipper.hichipper.log'`, it seems like it would be good to specify a relative path (this is the fault of the toolO

**Comment by Rseq** [comment]
Hi, 

So it did not work. I then removed hichipper to install again.
And now I cannot install. 
I'm receiving this error:

```
$ sudo -H pip install hichipper
Collecting hichipper
Requirement already satisfied: Numpy in /usr/lib/python2.7/dist-packages (from hichipper)
Collecting PyYAML (from hichipper)
  Downloading https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz (269kB)
    100% |████████████████████████████████| 276kB 818kB/s 
Collecting MACS2 (from hichipper)
  Using cached https://files.pythonhosted.org/packages/21/0f/972b44c84d85e37d816beae88aa5ddad606bd757630d77dc2f558900a6ce/MACS2-2.2.6.tar.gz
    Complete output from command python setup.py egg_info:
    CRITICAL: Python version must >= 3.6!
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-LUL8MX/MACS2/
```

If I use pip3, I get this one:

```
$ alias python=python3
$ python --version
Python 3.6.8
$ sudo -H pip3 install hichipper
Collecting hichipper
vRequirement already satisfied: MACS2 in /usr/local/lib/python3.6/dist-packages (from hichipper)
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from hichipper)
Requirement already satisfied: click in /usr/local/lib/python3.6/dist-packages (from hichipper)
Requirement already satisfied: whichcraft in /usr/local/lib/python3.6/dist-packages (from hichipper)
Requirement already satisfied: Numpy in /usr/local/lib/python3.6/dist-packages (from hichipper)
iInstalling collected packages: hichipper
Successfully installed hichipper-0.7.7
$ python --version
Python 3.6.8
$ hichipper --version
Traceback (most recent call last):
  File "/usr/local/bin/hichipper", line 7, in <module>
    from hichipper.cli import main
  File "/usr/local/lib/python3.6/dist-packages/hichipper/cli.py", line 131
    if make_ucsc or make_washu:
                              ^
TabError: inconsistent use of tabs and spaces in indentation
```

Any ideas what it can be?

**Comment by WeAllOneCode** [comment]
I got the same issue, installed with python 3.
Before "pip install" I fix the cli.py as follows.
--
    git clone https://github.com/aryeelab/hichipper.git && cd hichipper
    pip install autopep8
    autopep8 -i  hichipper/cli.py
    pip install .
--

**Comment by maharshi14** [comment]
> ## I got the same issue, installed with python 3.
> Before "pip install" I fix the cli.py as follows.
> ```
> git clone https://github.com/aryeelab/hichipper.git && cd hichipper
> pip install autopep8
> autopep8 -i  hichipper/cli.py
> pip install .
> ```
> 
> --

Works! Thank you
