### ISSUE TITLE
problem with python script

### ISSUE THREAD

**Issue by robeach78** [aryeelab/hichipper#90]
I am running hichipper for the first time and I run into this error:

Traceback (most recent call last):
  File "/users/mbeato/rferrari/.local/bin/hichipper", line 11, in <module>
    load_entry_point('hichipper==0.7.9', 'console_scripts', 'hichipper')()
  File "/software/as/el7.2/EasyBuild/CRG/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/software/as/el7.2/EasyBuild/CRG/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/software/as/el7.2/EasyBuild/CRG/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/software/as/el7.2/EasyBuild/CRG/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/users/mbeato/rferrari/.local/lib/python3.8/site-packages/hichipper-0.7.9-py3.8.egg/hichipper/cli.py", line 136
    if make_ucsc or make_washu:
                              ^
TabError: inconsistent use of tabs and spaces in indentation

what is this about?

Thanks a lot in advance.

R

**Comment by caleblareau** [comment]
Hi,

The tool was originally written with only python 2 support— that to me seems like the first thing to change (looks like you’re using python 3)

On Mar 18, 2021, at 2:20 PM, robeach78 ***@***.******@***.***>> wrote:



I am running hichipper for the first time and I run into this error:

Traceback (most recent call last):
File "/users/mbeato/rferrari/.local/bin/hichipper", line 11, in
load_entry_point('hichipper==0.7.9', 'console_scripts', 'hichipper')()
File "/software/as/el7.2/EasyBuild/CRG/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages/pkg_resources/init.py", line 489, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/software/as/el7.2/EasyBuild/CRG/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages/pkg_resources/init.py", line 2852, in load_entry_point
return ep.load()
File "/software/as/el7.2/EasyBuild/CRG/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages/pkg_resources/init.py", line 2443, in load
return self.resolve()
File "/software/as/el7.2/EasyBuild/CRG/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages/pkg_resources/init.py", line 2449, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "/users/mbeato/rferrari/.local/lib/python3.8/site-packages/hichipper-0.7.9-py3.8.egg/hichipper/cli.py", line 136
if make_ucsc or make_washu:
^
TabError: inconsistent use of tabs and spaces in indentation

what is this about?

Thanks a lot in advance.

R

**Comment by yanchunzhang** [comment]
HI, I also got the same issue.
I tried install to a python2 version but the MACS2 package will failed installation. While I installed it successfully under python3, then this error happen. What should I do to solve this?

Thanks,
Yanchun

**Comment by ntukirafang** [comment]
I also have the same issue.
Did anyone know how to install MACS2 under python3(such as Python 2.7)?
After installing MACS2, pip install hichipper can be solved.
In my case, I installed the MACS2.1.4 version(suitable for Python 2.7) and double check Cython version is 0.27.2.
Then, with python2.7  setup.py again, you will successfully install hichipper package.
